---
- hosts: websever
  become: yes

  vars:
    build_number: "{{ BUILD_NUMBER }}"
    image_name: "trialtypobk.jfrog.io/testapp/sampledockeruplaod"
    image_tag: "v.1.0.1-{{ build_number }}"

  tasks:

    - name: Login to JFrog
      docker_login:
        registry_url: trialtypobk.jfrog.io
        username: test
        password: Test@12345

    - name: Pull image
      docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: pull

    - name: Run container
      docker_container:
        name: devopsAppDeploy
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        recreate: yes
        ports:
          - "8111:8080"
